### ISSUE TITLE
Add ES6 support

### ISSUE THREAD

**Issue by zakangelle** [vigetlabs/grunt-complexity#35]
It would be nice to have ES6 support via a flag like `es6: true` or something similar.

**Comment by mdix** [comment]
+1

**Comment by isuttell** [comment]
Maybe a preprocessor option where we can transform the code first

**Comment by cristian-sima** [comment]
+1

**Comment by oliver-j** [comment]
+1

**Comment by adaniliuk** [comment]
Vote up

**Comment by kevde** [comment]
Can we help them to create new build for it?

**Comment by nhunzaker** [comment]
Sorry, I've neglected this repo...

First step would be to upgrade [`complexity-report`](https://github.com/escomplex/complexity-report). While we're at it, we should see if we can support other language compilers that are able to build a compatible AST (I'm hoping escomplex uses something like Acorn, but I don't know yet). 

Ideally, I want a way to build ASTs and send that to [escomplex](https://github.com/escomplex/escomplex). First, I'd like to know if this is even possible. Would anyone like to investigate this?

I also need to get up to speed on updates to `complexity-report` and any other tools that may solve this problem.

**Comment by kevde** [comment]
I will try to run a complexity report if they already support with their latest build. Hope this will help

**Comment by nhunzaker** [comment]
Awesome. Thank you!

**Comment by kevde** [comment]
I tried running cr to my directory with ES6 codes. It doesnt work yet. But as I was reviewing escomplex and https://github.com/escomplex/escomplex/issues/22 it supports ES6. I'll try tomorrow to refactor

**Comment by cristian-sima** [comment]
Guys, if you want to use something good to check ES6 please check [Eslint](http://eslint.org/). It is really good

**Comment by kevde** [comment]
I had researched about https://www.npmjs.com/package/typhonjs-escomplex and this supports ES6. I was reviewing packages used in plato (which now supports ES6)

**Comment by nhunzaker** [comment]
Cool. Awesome. I just made the migration to `escomplex` from `complexity-report`. I'll switch to that fork.

**Comment by nhunzaker** [comment]
Done. This is a pretty major change, so I've sent out a release candidate.

Would you all be willing to checkout `grunt-complexity@1.0.0-rc`?

**Comment by kevde** [comment]
I also have improvements with the current implementation. How can I push it from the repository?

**Comment by nhunzaker** [comment]
I'm happy to accept PRs. Feel free to fork `grunt-complexity` and send them along!

**Comment by nhunzaker** [comment]
Alright. Last run. Checkout `grunt-complexity@1.0.0-rc2`. I'll publish `1.0.0` later today.

**Comment by nhunzaker** [comment]
Alright. Thanks for your help @kevde This is shipped at `grunt-complexity@1.0.0`!

**Comment by typhonrt** [comment]
Thanks folks for adopting `typhonjs-escomplex`; I just noticed today. I didn't expect other projects outside of `plato` where I actively made the PR regarding early adoption. Let me know how I can help. There shouldn't be API breaking changes, however I'm soon releasing a significant update (0.0.13) for metric gathering for ES6+ that makes sense for ES Modules / classes in respect to Halstead / maintainability data gathered. In the next couple of weeks I hope to hit a stable `0.1.x` release. That way you can pin to `^0.1.0` rather than the specific release currently in grunt-complexity specifically limited to `0.0.12`. I definitely meant to get in touch with all potential downstream adopters when `0.1.0` is available, but indeed the desire to support ES6+ is strong; congrats folks for getting things going as soon as possible!

**Comment by nhunzaker** [comment]
Cool. Please keep us posted!
